### ISSUE TITLE
installing does not work on linux

### ISSUE THREAD

**Issue by deniskup** [sanderland/katrain#238]
When I try to install it, I get the following log:
```

 $ pip install katrain
Defaulting to user installation because normal site-packages is not writeable
Collecting katrain
  Using cached KaTrain-1.5.0-py3-none-any.whl (65.3 MB)
Requirement already satisfied: setuptools in /home/denis/.local/lib/python3.6/site-packages (from katrain) (50.3.2)
Requirement already satisfied: importlib-resources; python_version < "3.7" in /home/denis/.local/lib/python3.6/site-packages (from katrain) (3.0.0)
Requirement already satisfied: wheel in /home/denis/.local/lib/python3.6/site-packages (from katrain) (0.35.1)
Requirement already satisfied: cython!=0.27,!=0.27.2,<=0.29.14,>=0.24 in /home/denis/.local/lib/python3.6/site-packages (from katrain) (0.29.14)
Requirement already satisfied: screeninfo; platform_system != "Darwin" in /home/denis/.local/lib/python3.6/site-packages (from katrain) (0.6.5)
Requirement already satisfied: kivymd>=0.104.1 in /home/denis/.local/lib/python3.6/site-packages (from katrain) (0.104.1)
Requirement already satisfied: kivy==2.0.0rc2 in /home/denis/.local/lib/python3.6/site-packages (from katrain) (2.0.0rc2)
Requirement already satisfied: zipp>=0.4; python_version < "3.8" in /home/denis/.local/lib/python3.6/site-packages (from importlib-resources; python_version < "3.7"->katrain) (3.1.0)
Collecting pyobjus
  Using cached pyobjus-1.2.0.tar.gz (165 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 /home/denis/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp3q0dt0k1
       cwd: /tmp/pip-install-2awq_jnh/pyobjus
  Complete output (19 lines):
  Pyobjus platform is linux
  Traceback (most recent call last):
    File "/home/denis/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/home/denis/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/denis/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-xuwvjzkk/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 150, in get_requires_for_build_wheel
      config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-xuwvjzkk/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 130, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-xuwvjzkk/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 254, in run_setup
      self).run_setup(setup_script=setup_script)
    File "/tmp/pip-build-env-xuwvjzkk/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 145, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 35, in <module>
      class PyObjusBuildExt(build_ext, object):
  NameError: name 'build_ext' is not defined
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /home/denis/.local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp3q0dt0k1 Check the logs for full command output.
```

**Comment by sanderland** [comment]
Can you try python 3.7/3.8? They work for me on 1.6

**Comment by deniskup** [comment]
In the end I managed to install it by using "pip install katrain --no-deps".But having no GPU, katrain was not operational on my computer... I thought there was a CPU only version but apparently no.

**Comment by sanderland** [comment]
See https://github.com/sanderland/katrain#--configuring-katago for using cpu binaries
