### ISSUE TITLE
Crashes after upgrading from 1.5 to 1.6

### ISSUE THREAD

**Issue by limsherwin** [sanderland/katrain#246]
It took a while for me to get Katrain 1.5 running on my Lenovo E14 with Manjaro. Audio still didn't work. 

Upgraded to 1.6 few days ago, and it crashed when I tried to run it. Uninstalled and reinstalled, but still crashed. 

Turned the debug switch on, katrain  -d, and saw it was complaining about missing xclip, so I installed xclip. However, it still crashed when I ran the katrain with debugger on.

So I'm not sure if it's the issue with katrain or the install package.

NB: Cross-posted this issue at https://aur.archlinux.org/packages/katrain/ 

```

$ katrain -d    
[INFO   ] [Logger      ] Record log in /home/slim/.kivy/logs/kivy_20-11-26_10.txt
[INFO   ] [Kivy        ] v2.0.0rc2, git-Unknown, 20200808
[INFO   ] [Kivy        ] Installed at "/home/slim/.local/lib/python3.8/site-packages/kivy/__init__.py"
[INFO   ] [Python      ] v3.8.6 (default, Sep 30 2020, 04:00:38) 
[GCC 10.2.0]
[INFO   ] [Python      ] Interpreter at "/usr/bin/python"
[INFO   ] [Factory     ] 184 symbols loaded
[DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=None
[DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60
[DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=None
pygame 2.0.0 (SDL 2.0.12, python 3.8.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil (img_ffpyplayer, img_gif ignored)
[DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60
[DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600
[INFO   ] [Clipboard   ] Provider: xclip
[INFO   ] [CutBuffer   ] cut buffer support enabled
[DEBUG  ] [Text        ] Provider <pango> ignored by config
[INFO   ] [Text        ] Provider: pygame(['text_pango'] ignored)
[INFO   ] [Window      ] Provider: pygame
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /home/slim/.local/lib/python3.8/site-packages/kivy/core/window/window_pygame.py line 42.Called from /home/slim/.local/lib/python3.8/site-packages/kivy/core/__init__.py line 70 by core_select_lib().
[DEBUG  ] [Window      ] Display driver x11
[DEBUG  ] [Window      ] Actual window size: 1274x980
[DEBUG  ] [Window      ] Actual color bits r8 g8 b8 a0
[DEBUG  ] [Window      ] Actual depth bits: 24
[DEBUG  ] [Window      ] Actual stencil bits: 8
[DEBUG  ] [Window      ] Actual multisampling samples: 2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[DEBUG  ] [GL          ] glShaderBinary is not available
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'4.6 (Compatibility Profile) Mesa 20.2.2'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel'>
[INFO   ] [GL          ] OpenGL renderer <b'Mesa Intel(R) UHD Graphics (CML GT2)'>
[INFO   ] [GL          ] OpenGL parsed version: 4, 6
[INFO   ] [GL          ] Shading version <b'4.60'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <32>
[DEBUG  ] [Shader      ] Fragment compiled successfully
[DEBUG  ] [Shader      ] Vertex compiled successfully
[DEBUG  ] [ImagePygame ] Load </home/slim/.local/lib/python3.8/site-packages/kivy/data/glsl/default.png>
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /home/slim/.local/lib/python3.8/site-packages/kivy/core/image/img_pygame.py line 27.Called from /home/slim/.local/lib/python3.8/site-packages/kivy/core/image/__init__.py line 460 by load().
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [KivyMD      ] v0.104.1
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/rec_shadow.atlas>
[DEBUG  ] [Atlas       ] Need to load 2 images
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/rec_shadow-1.png>
[DEBUG  ] [ImagePygame ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/rec_shadow-1.png>
[INFO   ] [GL          ] NPOT texture support is available
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/rec_shadow-0.png>
[DEBUG  ] [ImagePygame ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/rec_shadow-0.png>
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/rec_st_shadow.atlas>
[DEBUG  ] [Atlas       ] Need to load 3 images
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/rec_st_shadow-0.png>
[DEBUG  ] [ImagePygame ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/rec_st_shadow-0.png>
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/rec_st_shadow-1.png>
[DEBUG  ] [ImagePygame ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/rec_st_shadow-1.png>
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/rec_st_shadow-2.png>
[DEBUG  ] [ImagePygame ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/rec_st_shadow-2.png>
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/quad_shadow.atlas>
[DEBUG  ] [Atlas       ] Need to load 3 images
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/quad_shadow-1.png>
[DEBUG  ] [ImagePygame ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/quad_shadow-1.png>
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/quad_shadow-0.png>
[DEBUG  ] [ImagePygame ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/quad_shadow-0.png>
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/quad_shadow-2.png>
[DEBUG  ] [ImagePygame ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/quad_shadow-2.png>
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/round_shadow.atlas>
[DEBUG  ] [Atlas       ] Need to load 3 images
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/round_shadow-1.png>
[DEBUG  ] [ImagePygame ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/round_shadow-1.png>
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/round_shadow-0.png>
[DEBUG  ] [ImagePygame ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/round_shadow-0.png>
[DEBUG  ] [Atlas       ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/round_shadow-2.png>
[DEBUG  ] [ImagePygame ] Load </home/slim/.local/lib/python3.8/site-packages/kivymd/images/round_shadow-2.png>
[DEBUG  ] [Cache       ] register <textinput.label> with limit=None, timeout=60.0
[DEBUG  ] [Cache       ] register <textinput.width> with limit=None, timeout=60.0
Using user config file /home/slim/.katrain/config.json
[WARNING] [Deprecated  ] Pygame has been deprecated and will be removed after 1.11.0: Call to deprecated function __init__ in /home/slim/.local/lib/python3.8/site-packages/kivy/core/text/text_pygame.py line 36.Called from /home/slim/.local/lib/python3.8/site-packages/kivy/uix/label.py line 349 by _create_label().
[WARNING] [Audio       ] Unable to find a loader for </usr/lib/python3.8/site-packages/katrain/sounds/stone1.wav>
[WARNING] [Audio       ] Unable to find a loader for </usr/lib/python3.8/site-packages/katrain/sounds/stone2.wav>
[WARNING] [Audio       ] Unable to find a loader for </usr/lib/python3.8/site-packages/katrain/sounds/stone3.wav>
[WARNING] [Audio       ] Unable to find a loader for </usr/lib/python3.8/site-packages/katrain/sounds/stone4.wav>
[WARNING] [Audio       ] Unable to find a loader for </usr/lib/python3.8/site-packages/katrain/sounds/stone5.wav>
[WARNING] [Audio       ] Unable to find a loader for </usr/lib/python3.8/site-packages/katrain/sounds/countdownbeep.wav>
[WARNING] [Audio       ] Unable to find a loader for </usr/lib/python3.8/site-packages/katrain/sounds/boing.wav>
 Traceback (most recent call last):
   File "/usr/bin/katrain", line 33, in <module>
     sys.exit(load_entry_point('KaTrain==1.6.0', 'console_scripts', 'katrain')())
   File "/usr/lib/python3.8/site-packages/katrain/__main__.py", line 609, in run_app
     app.run()
   File "/home/slim/.local/lib/python3.8/site-packages/kivy/app.py", line 949, in run
     self._run_prepare()
   File "/home/slim/.local/lib/python3.8/site-packages/kivy/app.py", line 919, in _run_prepare
     root = self.build()
   File "/usr/lib/python3.8/site-packages/katrain/__main__.py", line 551, in build
     self.gui = KaTrainGui()
   File "/usr/lib/python3.8/site-packages/katrain/__main__.py", line 89, in __init__
     super().__init__(**kwargs)
   File "/home/slim/.local/lib/python3.8/site-packages/kivy/uix/relativelayout.py", line 274, in __init__
     super(RelativeLayout, self).__init__(**kw)
   File "/home/slim/.local/lib/python3.8/site-packages/kivy/uix/floatlayout.py", line 65, in __init__
     super(FloatLayout, self).__init__(**kwargs)
   File "/home/slim/.local/lib/python3.8/site-packages/kivy/uix/layout.py", line 76, in __init__
     super(Layout, self).__init__(**kwargs)
   File "/home/slim/.local/lib/python3.8/site-packages/kivy/uix/widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "/home/slim/.local/lib/python3.8/site-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/home/slim/.local/lib/python3.8/site-packages/kivy/lang/builder.py", line 539, in apply
     self._apply_rule(
   File "/home/slim/.local/lib/python3.8/site-packages/kivy/lang/builder.py", line 661, in _apply_rule
     self._apply_rule(
   File "/home/slim/.local/lib/python3.8/site-packages/kivy/lang/builder.py", line 661, in _apply_rule
     self._apply_rule(
   File "/home/slim/.local/lib/python3.8/site-packages/kivy/lang/builder.py", line 661, in _apply_rule
     self._apply_rule(
   [Previous line repeated 2 more times]
   File "/home/slim/.local/lib/python3.8/site-packages/kivy/lang/builder.py", line 657, in _apply_rule
     child = cls(__no_builder=True)
   File "/usr/lib/python3.8/site-packages/katrain/gui/controlspanel.py", line 75, in __init__
     self.boing.volume = 0.1
 AttributeError: 'NoneType' object has no attribute 'volume'

```

**Comment by limsherwin** [comment]
I installed using the following instead: 

`pip3 install -U katrain
`

It now works, except for audio, which I still need to figure out.

**Comment by limsherwin** [comment]
The [INSTALL](https://github.com/sanderland/katrain/blob/master/INSTALL.md) file mentions to install Kivy 2.0.0**rc2** instead of whatever is was currently installed. However, it was mentioned [here](https://github.com/sanderland/katrain/issues/95#issuecomment-650525696) to use Kivy 2.0.0**rc3**

Now I have sounds and it works. Maybe the INSTALL file should be edited?
