### ISSUE TITLE
1.7.4 dll error / exit code 3221225501 on windows

### ISSUE THREAD

**Issue by mc-mong** [sanderland/katrain#349]
my computer system

ram 16g
vga 1070ti
cpu amd 8300

Using user config file C:\Users\mong\.katrain\config.json
2021-02-01 20:52:00+0900: Analysis Engine starting...
2021-02-01 20:52:00+0900: KataGo v1.8.0 (Minified for KaTrain v1.7.1)
2021-02-01 20:52:00+0900: nnRandSeed0 = 15719618078027842482
2021-02-01 20:52:00+0900: After dedups: nnModelFile0 = C:\Users\mong\Downloads\KaTrain\katrain\models/g170e-b15c192-s1672170752-d466197061.bin.gz useFP16 auto useNHWC auto
ERROR: Engine died unexpectedly without sending output, possibly due to out of memory: status 3221225501
ERROR: Engine died unexpectedly without sending output, possibly due to out of memory: status 3221225501
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "threading.py", line 932, in _bootstrap_inner
   File "threading.py", line 870, in run
   File "katrain\core\engine.py", line 204, in _analysis_read_thread
   File "katrain\core\engine.py", line 157, in check_alive
 katrain.core.engine.EngineDiedException: Engine died unexpectedly without sending output, possibly due to out of memory: status 3221225501

**Comment by sanderland** [comment]
That's a DLL error, not sure why it happens.
Try one of the official ones.

**Comment by xiaoyifang** [comment]
download new katago version ,using the function in the general setting dialog.choose katago version 1.8
