### ISSUE TITLE
KaTrain doesn't work after python update to 3.9

### ISSUE THREAD

**Issue by freysgodi** [sanderland/katrain#350]
Hello.
System Manjaro linux, nvidia driver, ocl-icd installed and works, Katrain works properly.
Just updated manjaro, so python updated from 3.8 to 3.9. After that KaTrain launching but engine doesn't work.

Console output:

> CRITICAL] [Cutbuffer   ] Unable to find any valuable Cutbuffer provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
xclip - FileNotFoundError: [Errno 2] Нет такого файла или каталога: 'xclip'
  File "/home/maxuzzz/.local/lib/python3.9/site-packages/kivy/core/__init__.py", line 58, in core_select_lib
    mod = __import__(name='{2}.{0}.{1}'.format(
  File "/home/maxuzzz/.local/lib/python3.9/site-packages/kivy/core/clipboard/clipboard_xclip.py", line 17, in <module>
    p = subprocess.Popen(['xclip', '-version'], stdout=subprocess.PIPE,
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

> xsel - FileNotFoundError: [Errno 2] Нет такого файла или каталога: 'xsel'
  File "/home/maxuzzz/.local/lib/python3.9/site-packages/kivy/core/__init__.py", line 58, in core_select_lib
    mod = __import__(name='{2}.{0}.{1}'.format(
  File "/home/maxuzzz/.local/lib/python3.9/site-packages/kivy/core/clipboard/clipboard_xsel.py", line 16, in <module>
    p = subprocess.Popen(['xsel'], stdout=subprocess.PIPE)
  File "/usr/lib/python3.9/subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1819, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)

> Using user config file /home/maxuzzz/.katrain/config.json
[CRITICAL] [AudioSDL2   ] Unable to open mixer: b'No such audio device'
[WARNING] [AudioSDL2   ] Unable to load /home/maxuzzz/.local/lib/python3.9/site-packages/katrain/sounds/stone1.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/maxuzzz/.local/lib/python3.9/site-packages/katrain/sounds/stone2.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/maxuzzz/.local/lib/python3.9/site-packages/katrain/sounds/stone3.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/maxuzzz/.local/lib/python3.9/site-packages/katrain/sounds/stone4.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/maxuzzz/.local/lib/python3.9/site-packages/katrain/sounds/stone5.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/maxuzzz/.local/lib/python3.9/site-packages/katrain/sounds/countdownbeep.wav: b"Audio device hasn't been opened"
[WARNING] [AudioSDL2   ] Unable to load /home/maxuzzz/.local/lib/python3.9/site-packages/katrain/sounds/boing.wav: b"Audio device hasn't been opened"
[WARNING] [MTD         ] Unable to open device "/dev/input/event9". Please ensure you have the appropriate permissions.
2021-02-02 10:34:47+0300: Analysis Engine starting...
2021-02-02 10:34:47+0300: KataGo 1.7.0+ (Minified version for KaTrain v1.7.1)
2021-02-02 10:34:47+0300: nnRandSeed0 = 9933839965278571400
2021-02-02 10:34:47+0300: After dedups: nnModelFile0 = /home/maxuzzz/.local/lib/python3.9/site-packages/katrain/models/g170e-b15c192-s1672170752-d466197061.bin.gz useFP16 auto useNHWC auto
terminate called after throwing an instance of 'StringError'
what():  OpenCL error at /KataGo/neuralnet/openclhelpers.cpp, func err, line 263, error CL_PLATFORM_NOT_FOUND_KHR
ERROR: Engine died unexpectedly without sending output, possibly due to out of memory: status -6
ERROR: Engine died unexpectedly without sending output, possibly due to out of memory: status -6
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.9/threading.py", line 892, in run
     self._target(*self._args, **self._kwargs)
   File "/home/maxuzzz/.local/lib/python3.9/site-packages/katrain/core/engine.py", line 204, in _analysis_read_thread
     self.check_alive(exception_if_dead=True)
   File "/home/maxuzzz/.local/lib/python3.9/site-packages/katrain/core/engine.py", line 157, in check_alive
     raise EngineDiedException(died_msg)
 katrain.core.engine.EngineDiedException: Engine died unexpectedly without sending output, possibly due to out of memory: status -6
--------------------------------------------------------------------------------
Also, installing KaTrain from pip on just installed new manjaro system get the same result.

**Comment by sanderland** [comment]
CL_PLATFORM_NOT_FOUND_KHR means something is wrong with your gpu/opencl setup. I occasionally get this on linux and it usually resolves in restart. You can also try the other executables in general settings

**Comment by freysgodi** [comment]
> CL_PLATFORM_NOT_FOUND_KHR means something is wrong with your gpu/opencl setup. I occasionally get this on linux and it usually resolves in restart. You can also try the other executables in general settings

for sure restart doesnt help :)

**Comment by freysgodi** [comment]
got it. it was a problem of opencl-nvidia after update. just need to install new opencl module.

katrain runs perfectly indeed
