### ISSUE TITLE
Cannot create a consistent method resolution Error

### ISSUE THREAD

**Issue by htang2012** [sanderland/katrain#440]
Traceback (most recent call last):
   File "/home/user/katrain/bin/katrain", line 5, in <module>
     from katrain.__main__ import run_app
   File "/home/user/katrain/lib/python3.8/site-packages/katrain/__main__.py", line 56, in <module>
     from katrain.gui.popups import ConfigTeacherPopup, ConfigTimerPopup, I18NPopup
   File "/home/user/katrain/lib/python3.8/site-packages/katrain/gui/popups.py", line 27, in <module>
     from katrain.gui.kivyutils import BackgroundMixin, I18NSpinner
   File "/home/user/katrain/lib/python3.8/site-packages/katrain/gui/kivyutils.py", line 67, in <module>
     class SizedButton(
 TypeError: Cannot create a consistent method resolution
 order (MRO) for bases ButtonBehavior, RectangularRippleBehavior, BasePressedButton, BaseFlatButton, BackgroundMixin

**Comment by sanderland** [comment]
and this is in a venv with the requirements as specified?

**Comment by htang2012** [comment]
Yes, Looks like this is a kivy related issue.

**Comment by htang2012** [comment]
instead of just issue: pip install -U katrain, I  git cloned the repository and launch pip install -r reqiurements.txt, it works after serveral struggles. hence closing this issue.
