### ISSUE TITLE
Can't get katago engine to run - Engine died 127 / libzip.so

### ISSUE THREAD

**Issue by Schneefloegge** [sanderland/katrain#464]
Hi everyone,

I am trying to get katrain to run on my machine (Ubuntu 18.04.5). My technical understanding is very limited, so I apologize beforehand :D.
Here's what I have tried so far: 
1. Run pip3 install katrain
2. Run pip3 install katrain in a venv
3. clone the katrain repo and run pip3 install .

All of these endeavours have always ended in this or a similar error message once I:  $ katrain

Using user config file /home/----/.katrain/config.json
/home/----/.katrain/katago-v1.9.1-eigen-linux-x64: error while loading shared libraries: libzip.so.5: cannot open shared object file: No such file or directory
ERROR: Engine died unexpectedly without sending output:  status 127
ERROR: Engine died unexpectedly without sending output:  status 127
 Exception in thread Thread-3:
 Traceback (most recent call last):
   File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
     self.run()
   File "/usr/lib/python3.6/threading.py", line 864, in run
     self._target(*self._args, **self._kwargs)
   File "/home/----/.local/lib/python3.6/site-packages/katrain/core/engine.py", line 324, in _write_stdin_thread
     self.katago_process.stdin.write((json.dumps(query) + "\n").encode())
 AttributeError: 'NoneType' object has no attribute 'stdin'
 
[WARNING] [MTD         ] Unable to open device "/dev/input/event16". Please ensure you have the appropriate permissions.

I have libzip-dev installed, but as I understand for Ubuntu 18 this comes with libzip.so.4 file, so katrain cannot find the right file.

Any help will be greatly appreciated, can't wait for this to work.

**Comment by sanderland** [comment]
The katago that ships with katrain is just the official opencl version (without debug strings for size) -- to support older libraries and such, recompile katago from source and point katrain to it in general settings.

**Comment by Schneefloegge** [comment]
How do I compile katago from source? What do I have to download and what do I need to run?

**Comment by sanderland** [comment]
https://github.com/lightvector/KataGo

**Comment by Schneefloegge** [comment]
Thanks, that worked!
