### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by andrewyli** [sanderland/katrain#6]
Hi, the program is currently looking for a nonexistent(?) file called 'katago' inside 'KataGo'.
```
Using config file config.json
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <sdl2>
[INFO   ] [GL          ] OpenGL version <b'2.1 INTEL-12.10.14'>
[INFO   ] [GL          ] OpenGL vendor <b'Intel Inc.'>
[INFO   ] [GL          ] OpenGL renderer <b'Intel(R) Iris(TM) Graphics 6100'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 1
[INFO   ] [GL          ] Shading version <b'1.20'>
[INFO   ] [GL          ] Texture max size <16384>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [GL          ] NPOT texture support is available
[INFO   ] [Base        ] Start application main loop
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
     self.run()
   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
     self._target(*self._args, **self._kwargs)
   File "/Users/andrewyli/Downloads/katrain/controller.py", line 61, in _engine_thread
     self.kata = subprocess.Popen(self.command, stdin=subprocess.PIPE, stdout=subprocess.PIPE)
   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
     restore_signals, start_new_session)
   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
     raise child_exception_type(errno_num, err_msg, err_filename)
 FileNotFoundError: [Errno 2] No such file or directory: 'KataGo/katago': 'KataGo/katago'
```

**Comment by andrewyli** [comment]
Ah apologies, this is on Mac and you've compiled an exe.

**Comment by sanderland** [comment]
Aha, this could be improved as an error. Do the Linux instructions work for mac?

**Comment by andrewyli** [comment]
They should, but the instructions are a bit vague. What's the compiled katago v1.3+ binary that I'm supposed to reference in the command?

**Comment by sanderland** [comment]
ah yes I'll add the URL to katago releases. which binary are you using, the linux ones?

**Comment by sanderland** [comment]
https://lifein19x19.com/viewtopic.php?f=18&t=16978  seems it may need compiling on mac. Having gone through this on linux, it's okay but the requirements are not quite complete,
